import {
  Activity,
  Library,
  RadioTower,
  ReceiptText,
  ShieldCheck,
  Sparkles,
  Swords,
} from "lucide-react";
import type { Project } from "./projects.types";

export const PROJECTS: Project[] = [
  {
    title: "Streanime / MyroniX",
    status: "Production UI",
    statusTone: "production",
    meta: "React 19 · TypeScript · Firebase · Vidstack",
    description: "A premium anime streaming and manga portal with custom episode playback, authentication, synced watchlists, reading history, and a secure administrator dashboard.",
    tags: ["React 19", "TypeScript", "Firebase", "Tailwind"],
    href: "https://aniwatchtv.tech",
    linkLabel: "Visit site",
    icon: Sparkles,
    search: "anime streaming manga vidstack firebase admin",
    image: "/myronix.png",
  },
  {
    title: "EndoBridge",
    status: "Deployed",
    statusTone: "production",
    meta: "React 18 · Vite · Node API · Gemini · MongoDB",
    description: "An AI-assisted PCOS monitoring companion that turns session and lab data into structured insight reports with validation, safety notices, PDF support, and test coverage.",
    tags: ["React", "TypeScript", "Gemini API", "Vitest"],
    href: "https://github.com/jonvicbarcenas/endobridge",
    liveHref: "https://endobridge.vercel.app",
    linkLabel: "Source code",
    icon: Activity,
    search: "health pcos ai report vite node mongodb",
  },
  {
    title: "QueueMS",
    status: "Active",
    statusTone: "active",
    meta: "Spring Boot · React · Android · Firestore",
    description: "Smart campus queue management with role-based workflows, teller handling, attachments, OAuth, email and push notifications, plus real-time WebSocket updates.",
    tags: ["Java", "TypeScript", "Kotlin"],
    href: "https://github.com/jonvicbarcenas/IT342_QueueMS_G4_Barcenas",
    linkLabel: "View repository",
    icon: RadioTower,
    search: "queue spring boot react android websocket firestore",
  },
  {
    title: "ShelfSmart",
    status: "Stable",
    statusTone: "stable",
    meta: "Django · PostgreSQL · SQLite · Bootstrap",
    description: "Library management for catalogs, members, borrowing, returns, reminders, search history, role-based dashboards, and administrator workflows.",
    tags: ["Django", "Python", "PostgreSQL"],
    href: "https://github.com/jonvicbarcenas/ShelfSmart",
    linkLabel: "View repository",
    icon: Library,
    search: "library django postgresql catalog borrowing",
  },
  {
    title: "Myrnhelm",
    status: "Game Lab",
    statusTone: "archive",
    meta: "Java OOP · libGDX",
    description: "A desktop RPG project exploring platform modules, NPCs, quests, JSON parsing, collision logic, and collaborative object-oriented game structure.",
    tags: ["Java", "OOP", "libGDX"],
    href: "https://github.com/jonvicbarcenas/Myrnhelm",
    linkLabel: "View repository",
    icon: Swords,
    search: "game java libgdx npc quest collision",
  },
  {
    title: "Auth Mini-App",
    status: "Lab",
    statusTone: "active",
    meta: "Spring Security · React · Android",
    description: "A full-stack authentication exercise with a Spring Boot backend, React client, Kotlin Android app, MySQL, Retrofit, and unified sign-in flows.",
    tags: ["Spring Boot", "React", "Kotlin"],
    href: "https://github.com/jonvicbarcenas/IT342_G4_Barcenas_Lab1",
    linkLabel: "View repository",
    icon: ShieldCheck,
    search: "authentication security spring react kotlin mysql",
  },
  {
    title: "Django POS",
    status: "Practice",
    statusTone: "stable",
    meta: "Django · SQLite · HTML/CSS/JS",
    description: "A point-of-sale system with administrator, manager, and teller roles, product management, transaction processing, and sales reporting.",
    tags: ["Python", "Django", "RBAC"],
    href: "https://github.com/jonvicbarcenas/django-pos-system",
    linkLabel: "View repository",
    icon: ReceiptText,
    search: "django point of sale roles reports transaction",
  },
];

export function projectSearchText(project: Project) {
  return `${project.title} ${project.meta} ${project.description} ${project.tags.join(" ")} ${project.search}`.toLowerCase();
}
